//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("sistemardcModel", "IDCLIENTE", "clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(rdc.Models.cliente), "reclamacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.reclamaco), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "IDFORNECEDOR", "fornecedores", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(rdc.Models.fornecedore), "reclamacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.reclamaco), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "FKIDCIDADES", "cidade", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(rdc.Models.cidade), "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.cliente), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "FKIDCIDFOR", "cidade", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(rdc.Models.cidade), "fornecedore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.fornecedore), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "FKINTIDCLI", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(rdc.Models.cliente), "interaco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.interaco), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "FKINTIDRECL", "reclamaco", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(rdc.Models.reclamaco), "interaco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.interaco), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "FKIDFONEC", "fornecedore", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(rdc.Models.fornecedore), "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.cliente), true)]
[assembly: EdmRelationshipAttribute("sistemardcModel", "FKIDCLIFOR", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(rdc.Models.cliente), "fornecedore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(rdc.Models.fornecedore), true)]

#endregion

namespace rdc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sistemardcEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sistemardcEntities object using the connection string found in the 'sistemardcEntities' section of the application configuration file.
        /// </summary>
        public sistemardcEntities() : base("name=sistemardcEntities", "sistemardcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sistemardcEntities object.
        /// </summary>
        public sistemardcEntities(string connectionString) : base(connectionString, "sistemardcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sistemardcEntities object.
        /// </summary>
        public sistemardcEntities(EntityConnection connection) : base(connection, "sistemardcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cliente> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<cliente>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<cliente> _clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<fornecedore> fornecedores
        {
            get
            {
                if ((_fornecedores == null))
                {
                    _fornecedores = base.CreateObjectSet<fornecedore>("fornecedores");
                }
                return _fornecedores;
            }
        }
        private ObjectSet<fornecedore> _fornecedores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<reclamaco> reclamacoes
        {
            get
            {
                if ((_reclamacoes == null))
                {
                    _reclamacoes = base.CreateObjectSet<reclamaco>("reclamacoes");
                }
                return _reclamacoes;
            }
        }
        private ObjectSet<reclamaco> _reclamacoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cidade> cidades
        {
            get
            {
                if ((_cidades == null))
                {
                    _cidades = base.CreateObjectSet<cidade>("cidades");
                }
                return _cidades;
            }
        }
        private ObjectSet<cidade> _cidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<interaco> interacoes
        {
            get
            {
                if ((_interacoes == null))
                {
                    _interacoes = base.CreateObjectSet<interaco>("interacoes");
                }
                return _interacoes;
            }
        }
        private ObjectSet<interaco> _interacoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclientes(cliente cliente)
        {
            base.AddObject("clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fornecedores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofornecedores(fornecedore fornecedore)
        {
            base.AddObject("fornecedores", fornecedore);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the reclamacoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToreclamacoes(reclamaco reclamaco)
        {
            base.AddObject("reclamacoes", reclamaco);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocidades(cidade cidade)
        {
            base.AddObject("cidades", cidade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the interacoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTointeracoes(interaco interaco)
        {
            base.AddObject("interacoes", interaco);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sistemardcModel", Name="cidade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cidade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cidade object.
        /// </summary>
        /// <param name="iDCIDADE">Initial value of the IDCIDADE property.</param>
        public static cidade Createcidade(global::System.Int32 iDCIDADE)
        {
            cidade cidade = new cidade();
            cidade.IDCIDADE = iDCIDADE;
            return cidade;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCIDADE
        {
            get
            {
                return _IDCIDADE;
            }
            set
            {
                if (_IDCIDADE != value)
                {
                    OnIDCIDADEChanging(value);
                    ReportPropertyChanging("IDCIDADE");
                    _IDCIDADE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCIDADE");
                    OnIDCIDADEChanged();
                }
            }
        }
        private global::System.Int32 _IDCIDADE;
        partial void OnIDCIDADEChanging(global::System.Int32 value);
        partial void OnIDCIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMECIDADE
        {
            get
            {
                return _NOMECIDADE;
            }
            set
            {
                OnNOMECIDADEChanging(value);
                ReportPropertyChanging("NOMECIDADE");
                _NOMECIDADE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMECIDADE");
                OnNOMECIDADEChanged();
            }
        }
        private global::System.String _NOMECIDADE;
        partial void OnNOMECIDADEChanging(global::System.String value);
        partial void OnNOMECIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDESTADO
        {
            get
            {
                return _IDESTADO;
            }
            set
            {
                OnIDESTADOChanging(value);
                ReportPropertyChanging("IDESTADO");
                _IDESTADO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDESTADO");
                OnIDESTADOChanged();
            }
        }
        private global::System.String _IDESTADO;
        partial void OnIDESTADOChanging(global::System.String value);
        partial void OnIDESTADOChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDCIDADES", "cliente")]
        public EntityCollection<cliente> clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cliente>("sistemardcModel.FKIDCIDADES", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cliente>("sistemardcModel.FKIDCIDADES", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDCIDFOR", "fornecedore")]
        public EntityCollection<fornecedore> fornecedores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fornecedore>("sistemardcModel.FKIDCIDFOR", "fornecedore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fornecedore>("sistemardcModel.FKIDCIDFOR", "fornecedore", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sistemardcModel", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cliente object.
        /// </summary>
        /// <param name="iDCLIENTE">Initial value of the IDCLIENTE property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        /// <param name="lOGIN">Initial value of the LOGIN property.</param>
        /// <param name="sENHA">Initial value of the SENHA property.</param>
        /// <param name="cONFIRMASENHA">Initial value of the CONFIRMASENHA property.</param>
        public static cliente Createcliente(global::System.Int32 iDCLIENTE, global::System.String nOME, global::System.String eMAIL, global::System.String lOGIN, global::System.String sENHA, global::System.String cONFIRMASENHA)
        {
            cliente cliente = new cliente();
            cliente.IDCLIENTE = iDCLIENTE;
            cliente.NOME = nOME;
            cliente.EMAIL = eMAIL;
            cliente.LOGIN = lOGIN;
            cliente.SENHA = sENHA;
            cliente.CONFIRMASENHA = cONFIRMASENHA;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCLIENTE
        {
            get
            {
                return _IDCLIENTE;
            }
            set
            {
                if (_IDCLIENTE != value)
                {
                    OnIDCLIENTEChanging(value);
                    ReportPropertyChanging("IDCLIENTE");
                    _IDCLIENTE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCLIENTE");
                    OnIDCLIENTEChanged();
                }
            }
        }
        private global::System.Int32 _IDCLIENTE;
        partial void OnIDCLIENTEChanging(global::System.Int32 value);
        partial void OnIDCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RG
        {
            get
            {
                return _RG;
            }
            set
            {
                OnRGChanging(value);
                ReportPropertyChanging("RG");
                _RG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RG");
                OnRGChanged();
            }
        }
        private global::System.String _RG;
        partial void OnRGChanging(global::System.String value);
        partial void OnRGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENDERECO
        {
            get
            {
                return _ENDERECO;
            }
            set
            {
                OnENDERECOChanging(value);
                ReportPropertyChanging("ENDERECO");
                _ENDERECO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENDERECO");
                OnENDERECOChanged();
            }
        }
        private global::System.String _ENDERECO;
        partial void OnENDERECOChanging(global::System.String value);
        partial void OnENDERECOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FONEFIXO
        {
            get
            {
                return _FONEFIXO;
            }
            set
            {
                OnFONEFIXOChanging(value);
                ReportPropertyChanging("FONEFIXO");
                _FONEFIXO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FONEFIXO");
                OnFONEFIXOChanged();
            }
        }
        private global::System.String _FONEFIXO;
        partial void OnFONEFIXOChanging(global::System.String value);
        partial void OnFONEFIXOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FONECELULAR
        {
            get
            {
                return _FONECELULAR;
            }
            set
            {
                OnFONECELULARChanging(value);
                ReportPropertyChanging("FONECELULAR");
                _FONECELULAR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FONECELULAR");
                OnFONECELULARChanged();
            }
        }
        private global::System.String _FONECELULAR;
        partial void OnFONECELULARChanging(global::System.String value);
        partial void OnFONECELULARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NASCIMENTO
        {
            get
            {
                return _NASCIMENTO;
            }
            set
            {
                OnNASCIMENTOChanging(value);
                ReportPropertyChanging("NASCIMENTO");
                _NASCIMENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NASCIMENTO");
                OnNASCIMENTOChanged();
            }
        }
        private Nullable<global::System.DateTime> _NASCIMENTO;
        partial void OnNASCIMENTOChanging(Nullable<global::System.DateTime> value);
        partial void OnNASCIMENTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INFORMACOES
        {
            get
            {
                return _INFORMACOES;
            }
            set
            {
                OnINFORMACOESChanging(value);
                ReportPropertyChanging("INFORMACOES");
                _INFORMACOES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INFORMACOES");
                OnINFORMACOESChanged();
            }
        }
        private global::System.String _INFORMACOES;
        partial void OnINFORMACOESChanging(global::System.String value);
        partial void OnINFORMACOESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIPOCLIENTE
        {
            get
            {
                return _TIPOCLIENTE;
            }
            set
            {
                OnTIPOCLIENTEChanging(value);
                ReportPropertyChanging("TIPOCLIENTE");
                _TIPOCLIENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIPOCLIENTE");
                OnTIPOCLIENTEChanged();
            }
        }
        private global::System.String _TIPOCLIENTE;
        partial void OnTIPOCLIENTEChanging(global::System.String value);
        partial void OnTIPOCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                OnLOGINChanging(value);
                ReportPropertyChanging("LOGIN");
                _LOGIN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOGIN");
                OnLOGINChanged();
            }
        }
        private global::System.String _LOGIN;
        partial void OnLOGINChanging(global::System.String value);
        partial void OnLOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SENHA
        {
            get
            {
                return _SENHA;
            }
            set
            {
                OnSENHAChanging(value);
                ReportPropertyChanging("SENHA");
                _SENHA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SENHA");
                OnSENHAChanged();
            }
        }
        private global::System.String _SENHA;
        partial void OnSENHAChanging(global::System.String value);
        partial void OnSENHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONFIRMASENHA
        {
            get
            {
                return _CONFIRMASENHA;
            }
            set
            {
                OnCONFIRMASENHAChanging(value);
                ReportPropertyChanging("CONFIRMASENHA");
                _CONFIRMASENHA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONFIRMASENHA");
                OnCONFIRMASENHAChanged();
            }
        }
        private global::System.String _CONFIRMASENHA;
        partial void OnCONFIRMASENHAChanging(global::System.String value);
        partial void OnCONFIRMASENHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCIDADE
        {
            get
            {
                return _IDCIDADE;
            }
            set
            {
                OnIDCIDADEChanging(value);
                ReportPropertyChanging("IDCIDADE");
                _IDCIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCIDADE");
                OnIDCIDADEChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCIDADE;
        partial void OnIDCIDADEChanging(Nullable<global::System.Int32> value);
        partial void OnIDCIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDFORNECEDOR
        {
            get
            {
                return _IDFORNECEDOR;
            }
            set
            {
                OnIDFORNECEDORChanging(value);
                ReportPropertyChanging("IDFORNECEDOR");
                _IDFORNECEDOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFORNECEDOR");
                OnIDFORNECEDORChanged();
            }
        }
        private Nullable<global::System.Int32> _IDFORNECEDOR;
        partial void OnIDFORNECEDORChanging(Nullable<global::System.Int32> value);
        partial void OnIDFORNECEDORChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "IDCLIENTE", "reclamacoes")]
        public EntityCollection<reclamaco> reclamacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<reclamaco>("sistemardcModel.IDCLIENTE", "reclamacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<reclamaco>("sistemardcModel.IDCLIENTE", "reclamacoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDCIDADES", "cidade")]
        public cidade cidade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cidade>("sistemardcModel.FKIDCIDADES", "cidade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cidade>("sistemardcModel.FKIDCIDADES", "cidade").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cidade> cidadeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cidade>("sistemardcModel.FKIDCIDADES", "cidade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cidade>("sistemardcModel.FKIDCIDADES", "cidade", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKINTIDCLI", "interaco")]
        public EntityCollection<interaco> interacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<interaco>("sistemardcModel.FKINTIDCLI", "interaco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<interaco>("sistemardcModel.FKINTIDCLI", "interaco", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDFONEC", "fornecedore")]
        public fornecedore fornecedore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedore>("sistemardcModel.FKIDFONEC", "fornecedore").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedore>("sistemardcModel.FKIDFONEC", "fornecedore").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<fornecedore> fornecedoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedore>("sistemardcModel.FKIDFONEC", "fornecedore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<fornecedore>("sistemardcModel.FKIDFONEC", "fornecedore", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDCLIFOR", "fornecedore")]
        public EntityCollection<fornecedore> fornecedores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fornecedore>("sistemardcModel.FKIDCLIFOR", "fornecedore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fornecedore>("sistemardcModel.FKIDCLIFOR", "fornecedore", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sistemardcModel", Name="fornecedore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fornecedore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new fornecedore object.
        /// </summary>
        /// <param name="iDFORNECEDOR">Initial value of the IDFORNECEDOR property.</param>
        /// <param name="razaosocial">Initial value of the razaosocial property.</param>
        /// <param name="nomefantasia">Initial value of the nomefantasia property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="ativo">Initial value of the ativo property.</param>
        /// <param name="eNVEMAILCLISOL">Initial value of the ENVEMAILCLISOL property.</param>
        public static fornecedore Createfornecedore(global::System.Int32 iDFORNECEDOR, global::System.String razaosocial, global::System.String nomefantasia, global::System.String email, global::System.String ativo, global::System.String eNVEMAILCLISOL)
        {
            fornecedore fornecedore = new fornecedore();
            fornecedore.IDFORNECEDOR = iDFORNECEDOR;
            fornecedore.razaosocial = razaosocial;
            fornecedore.nomefantasia = nomefantasia;
            fornecedore.email = email;
            fornecedore.ativo = ativo;
            fornecedore.ENVEMAILCLISOL = eNVEMAILCLISOL;
            return fornecedore;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFORNECEDOR
        {
            get
            {
                return _IDFORNECEDOR;
            }
            set
            {
                if (_IDFORNECEDOR != value)
                {
                    OnIDFORNECEDORChanging(value);
                    ReportPropertyChanging("IDFORNECEDOR");
                    _IDFORNECEDOR = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFORNECEDOR");
                    OnIDFORNECEDORChanged();
                }
            }
        }
        private global::System.Int32 _IDFORNECEDOR;
        partial void OnIDFORNECEDORChanging(global::System.Int32 value);
        partial void OnIDFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String razaosocial
        {
            get
            {
                return _razaosocial;
            }
            set
            {
                OnrazaosocialChanging(value);
                ReportPropertyChanging("razaosocial");
                _razaosocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("razaosocial");
                OnrazaosocialChanged();
            }
        }
        private global::System.String _razaosocial;
        partial void OnrazaosocialChanging(global::System.String value);
        partial void OnrazaosocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomefantasia
        {
            get
            {
                return _nomefantasia;
            }
            set
            {
                OnnomefantasiaChanging(value);
                ReportPropertyChanging("nomefantasia");
                _nomefantasia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomefantasia");
                OnnomefantasiaChanged();
            }
        }
        private global::System.String _nomefantasia;
        partial void OnnomefantasiaChanging(global::System.String value);
        partial void OnnomefantasiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cnpj
        {
            get
            {
                return _cnpj;
            }
            set
            {
                OncnpjChanging(value);
                ReportPropertyChanging("cnpj");
                _cnpj = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cnpj");
                OncnpjChanged();
            }
        }
        private global::System.String _cnpj;
        partial void OncnpjChanging(global::System.String value);
        partial void OncnpjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fonefixo
        {
            get
            {
                return _fonefixo;
            }
            set
            {
                OnfonefixoChanging(value);
                ReportPropertyChanging("fonefixo");
                _fonefixo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fonefixo");
                OnfonefixoChanged();
            }
        }
        private global::System.String _fonefixo;
        partial void OnfonefixoChanging(global::System.String value);
        partial void OnfonefixoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fonefixo2
        {
            get
            {
                return _fonefixo2;
            }
            set
            {
                Onfonefixo2Changing(value);
                ReportPropertyChanging("fonefixo2");
                _fonefixo2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fonefixo2");
                Onfonefixo2Changed();
            }
        }
        private global::System.String _fonefixo2;
        partial void Onfonefixo2Changing(global::System.String value);
        partial void Onfonefixo2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String informacoes
        {
            get
            {
                return _informacoes;
            }
            set
            {
                OninformacoesChanging(value);
                ReportPropertyChanging("informacoes");
                _informacoes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("informacoes");
                OninformacoesChanged();
            }
        }
        private global::System.String _informacoes;
        partial void OninformacoesChanging(global::System.String value);
        partial void OninformacoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCIDADE
        {
            get
            {
                return _IDCIDADE;
            }
            set
            {
                OnIDCIDADEChanging(value);
                ReportPropertyChanging("IDCIDADE");
                _IDCIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCIDADE");
                OnIDCIDADEChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCIDADE;
        partial void OnIDCIDADEChanging(Nullable<global::System.Int32> value);
        partial void OnIDCIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ativo
        {
            get
            {
                return _ativo;
            }
            set
            {
                OnativoChanging(value);
                ReportPropertyChanging("ativo");
                _ativo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ativo");
                OnativoChanged();
            }
        }
        private global::System.String _ativo;
        partial void OnativoChanging(global::System.String value);
        partial void OnativoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String homepage
        {
            get
            {
                return _homepage;
            }
            set
            {
                OnhomepageChanging(value);
                ReportPropertyChanging("homepage");
                _homepage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("homepage");
                OnhomepageChanged();
            }
        }
        private global::System.String _homepage;
        partial void OnhomepageChanging(global::System.String value);
        partial void OnhomepageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCLIENTE
        {
            get
            {
                return _IDCLIENTE;
            }
            set
            {
                OnIDCLIENTEChanging(value);
                ReportPropertyChanging("IDCLIENTE");
                _IDCLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCLIENTE");
                OnIDCLIENTEChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCLIENTE;
        partial void OnIDCLIENTEChanging(Nullable<global::System.Int32> value);
        partial void OnIDCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENVEMAILCLISOL
        {
            get
            {
                return _ENVEMAILCLISOL;
            }
            set
            {
                OnENVEMAILCLISOLChanging(value);
                ReportPropertyChanging("ENVEMAILCLISOL");
                _ENVEMAILCLISOL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ENVEMAILCLISOL");
                OnENVEMAILCLISOLChanged();
            }
        }
        private global::System.String _ENVEMAILCLISOL;
        partial void OnENVEMAILCLISOLChanging(global::System.String value);
        partial void OnENVEMAILCLISOLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "IDFORNECEDOR", "reclamacoes")]
        public EntityCollection<reclamaco> reclamacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<reclamaco>("sistemardcModel.IDFORNECEDOR", "reclamacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<reclamaco>("sistemardcModel.IDFORNECEDOR", "reclamacoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDCIDFOR", "cidade")]
        public cidade cidade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cidade>("sistemardcModel.FKIDCIDFOR", "cidade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cidade>("sistemardcModel.FKIDCIDFOR", "cidade").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cidade> cidadeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cidade>("sistemardcModel.FKIDCIDFOR", "cidade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cidade>("sistemardcModel.FKIDCIDFOR", "cidade", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDFONEC", "cliente")]
        public EntityCollection<cliente> clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cliente>("sistemardcModel.FKIDFONEC", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cliente>("sistemardcModel.FKIDFONEC", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKIDCLIFOR", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.FKIDCLIFOR", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.FKIDCLIFOR", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.FKIDCLIFOR", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("sistemardcModel.FKIDCLIFOR", "cliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sistemardcModel", Name="interaco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class interaco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new interaco object.
        /// </summary>
        /// <param name="iDINTERACAO">Initial value of the IDINTERACAO property.</param>
        /// <param name="iNFORMACOES">Initial value of the INFORMACOES property.</param>
        /// <param name="dATAINTERACAO">Initial value of the DATAINTERACAO property.</param>
        /// <param name="iDRECLAMACAO">Initial value of the IDRECLAMACAO property.</param>
        /// <param name="iDCLIENTE">Initial value of the IDCLIENTE property.</param>
        public static interaco Createinteraco(global::System.Int32 iDINTERACAO, global::System.String iNFORMACOES, global::System.DateTime dATAINTERACAO, global::System.Int32 iDRECLAMACAO, global::System.Int32 iDCLIENTE)
        {
            interaco interaco = new interaco();
            interaco.IDINTERACAO = iDINTERACAO;
            interaco.INFORMACOES = iNFORMACOES;
            interaco.DATAINTERACAO = dATAINTERACAO;
            interaco.IDRECLAMACAO = iDRECLAMACAO;
            interaco.IDCLIENTE = iDCLIENTE;
            return interaco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDINTERACAO
        {
            get
            {
                return _IDINTERACAO;
            }
            set
            {
                if (_IDINTERACAO != value)
                {
                    OnIDINTERACAOChanging(value);
                    ReportPropertyChanging("IDINTERACAO");
                    _IDINTERACAO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDINTERACAO");
                    OnIDINTERACAOChanged();
                }
            }
        }
        private global::System.Int32 _IDINTERACAO;
        partial void OnIDINTERACAOChanging(global::System.Int32 value);
        partial void OnIDINTERACAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String INFORMACOES
        {
            get
            {
                return _INFORMACOES;
            }
            set
            {
                OnINFORMACOESChanging(value);
                ReportPropertyChanging("INFORMACOES");
                _INFORMACOES = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("INFORMACOES");
                OnINFORMACOESChanged();
            }
        }
        private global::System.String _INFORMACOES;
        partial void OnINFORMACOESChanging(global::System.String value);
        partial void OnINFORMACOESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATAINTERACAO
        {
            get
            {
                return _DATAINTERACAO;
            }
            set
            {
                OnDATAINTERACAOChanging(value);
                ReportPropertyChanging("DATAINTERACAO");
                _DATAINTERACAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATAINTERACAO");
                OnDATAINTERACAOChanged();
            }
        }
        private global::System.DateTime _DATAINTERACAO;
        partial void OnDATAINTERACAOChanging(global::System.DateTime value);
        partial void OnDATAINTERACAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDRECLAMACAO
        {
            get
            {
                return _IDRECLAMACAO;
            }
            set
            {
                OnIDRECLAMACAOChanging(value);
                ReportPropertyChanging("IDRECLAMACAO");
                _IDRECLAMACAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDRECLAMACAO");
                OnIDRECLAMACAOChanged();
            }
        }
        private global::System.Int32 _IDRECLAMACAO;
        partial void OnIDRECLAMACAOChanging(global::System.Int32 value);
        partial void OnIDRECLAMACAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCLIENTE
        {
            get
            {
                return _IDCLIENTE;
            }
            set
            {
                OnIDCLIENTEChanging(value);
                ReportPropertyChanging("IDCLIENTE");
                _IDCLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCLIENTE");
                OnIDCLIENTEChanged();
            }
        }
        private global::System.Int32 _IDCLIENTE;
        partial void OnIDCLIENTEChanging(global::System.Int32 value);
        partial void OnIDCLIENTEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKINTIDCLI", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.FKINTIDCLI", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.FKINTIDCLI", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.FKINTIDCLI", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("sistemardcModel.FKINTIDCLI", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKINTIDRECL", "reclamaco")]
        public reclamaco reclamaco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<reclamaco>("sistemardcModel.FKINTIDRECL", "reclamaco").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<reclamaco>("sistemardcModel.FKINTIDRECL", "reclamaco").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<reclamaco> reclamacoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<reclamaco>("sistemardcModel.FKINTIDRECL", "reclamaco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<reclamaco>("sistemardcModel.FKINTIDRECL", "reclamaco", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sistemardcModel", Name="reclamaco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class reclamaco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new reclamaco object.
        /// </summary>
        /// <param name="idreclamacao">Initial value of the idreclamacao property.</param>
        /// <param name="titulo">Initial value of the titulo property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="tiposolucao">Initial value of the tiposolucao property.</param>
        /// <param name="iDCLIENTE">Initial value of the IDCLIENTE property.</param>
        /// <param name="iDFORNECEDOR">Initial value of the IDFORNECEDOR property.</param>
        public static reclamaco Createreclamaco(global::System.Int32 idreclamacao, global::System.String titulo, global::System.String descricao, global::System.String tiposolucao, global::System.Int32 iDCLIENTE, global::System.Int32 iDFORNECEDOR)
        {
            reclamaco reclamaco = new reclamaco();
            reclamaco.idreclamacao = idreclamacao;
            reclamaco.titulo = titulo;
            reclamaco.descricao = descricao;
            reclamaco.tiposolucao = tiposolucao;
            reclamaco.IDCLIENTE = iDCLIENTE;
            reclamaco.IDFORNECEDOR = iDFORNECEDOR;
            return reclamaco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idreclamacao
        {
            get
            {
                return _idreclamacao;
            }
            set
            {
                if (_idreclamacao != value)
                {
                    OnidreclamacaoChanging(value);
                    ReportPropertyChanging("idreclamacao");
                    _idreclamacao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idreclamacao");
                    OnidreclamacaoChanged();
                }
            }
        }
        private global::System.Int32 _idreclamacao;
        partial void OnidreclamacaoChanging(global::System.Int32 value);
        partial void OnidreclamacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tiposolucao
        {
            get
            {
                return _tiposolucao;
            }
            set
            {
                OntiposolucaoChanging(value);
                ReportPropertyChanging("tiposolucao");
                _tiposolucao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tiposolucao");
                OntiposolucaoChanged();
            }
        }
        private global::System.String _tiposolucao;
        partial void OntiposolucaoChanging(global::System.String value);
        partial void OntiposolucaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCLIENTE
        {
            get
            {
                return _IDCLIENTE;
            }
            set
            {
                OnIDCLIENTEChanging(value);
                ReportPropertyChanging("IDCLIENTE");
                _IDCLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCLIENTE");
                OnIDCLIENTEChanged();
            }
        }
        private global::System.Int32 _IDCLIENTE;
        partial void OnIDCLIENTEChanging(global::System.Int32 value);
        partial void OnIDCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFORNECEDOR
        {
            get
            {
                return _IDFORNECEDOR;
            }
            set
            {
                OnIDFORNECEDORChanging(value);
                ReportPropertyChanging("IDFORNECEDOR");
                _IDFORNECEDOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFORNECEDOR");
                OnIDFORNECEDORChanged();
            }
        }
        private global::System.Int32 _IDFORNECEDOR;
        partial void OnIDFORNECEDORChanging(global::System.Int32 value);
        partial void OnIDFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datacompra
        {
            get
            {
                return _datacompra;
            }
            set
            {
                OndatacompraChanging(value);
                ReportPropertyChanging("datacompra");
                _datacompra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datacompra");
                OndatacompraChanged();
            }
        }
        private Nullable<global::System.DateTime> _datacompra;
        partial void OndatacompraChanging(Nullable<global::System.DateTime> value);
        partial void OndatacompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fonecontato
        {
            get
            {
                return _fonecontato;
            }
            set
            {
                OnfonecontatoChanging(value);
                ReportPropertyChanging("fonecontato");
                _fonecontato = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fonecontato");
                OnfonecontatoChanged();
            }
        }
        private global::System.String _fonecontato;
        partial void OnfonecontatoChanging(global::System.String value);
        partial void OnfonecontatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datasolucao
        {
            get
            {
                return _datasolucao;
            }
            set
            {
                OndatasolucaoChanging(value);
                ReportPropertyChanging("datasolucao");
                _datasolucao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datasolucao");
                OndatasolucaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _datasolucao;
        partial void OndatasolucaoChanging(Nullable<global::System.DateTime> value);
        partial void OndatasolucaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "IDCLIENTE", "clientes")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.IDCLIENTE", "clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.IDCLIENTE", "clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("sistemardcModel.IDCLIENTE", "clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("sistemardcModel.IDCLIENTE", "clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "IDFORNECEDOR", "fornecedores")]
        public fornecedore fornecedore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedore>("sistemardcModel.IDFORNECEDOR", "fornecedores").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedore>("sistemardcModel.IDFORNECEDOR", "fornecedores").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<fornecedore> fornecedoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedore>("sistemardcModel.IDFORNECEDOR", "fornecedores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<fornecedore>("sistemardcModel.IDFORNECEDOR", "fornecedores", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sistemardcModel", "FKINTIDRECL", "interaco")]
        public EntityCollection<interaco> interacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<interaco>("sistemardcModel.FKINTIDRECL", "interaco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<interaco>("sistemardcModel.FKINTIDRECL", "interaco", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
